- hosts: all
  remote_user: bgiarrizzo
  roles:
    # - security
    # - fail2ban
    - nginx
    # - geerlingguy.docker
    # - irc
    # - webhooks
    # - seedbox
    - websites
    # - glance
    # - mediacenter
    # - newsreaders
    # - retroarch
