---

newsreaders_path_to_config_on_host: /media/Store/apps

certbot_email: bruno@giarrizzo.fr

newsreader_apps:
  - name: freshrss
    nginx:
      server_name: freshrss.giarrizzo.fr
      https: true
    docker:
      image:
        name: linuxserver/freshrss
        tag: latest
      restart: unless-stopped
      volumes:
        - "{{ newsreaders_path_to_config_on_host }}/freshrss/:/config:rw"
      ports:
        - "8555:80"
      recreate: true
  - name: wallabag
    nginx:
      server_name: wallabag.giarrizzo.fr
      https: true
    docker:
      image:
        name: wallabag/wallabag
        tag: latest
      restart: unless-stopped
      environment:
        SYMFONY__ENV__DOMAIN_NAME: https://wallabag.giarrizzo.fr
      volumes:
        - "{{ newsreaders_path_to_config_on_host }}/wallabag/images:/var/www/wallabag/web/assets/images:rw"
        - "{{ newsreaders_path_to_config_on_host }}/wallabag/data:/var/www/wallabag/data:rw"
      ports:
        - "8081:80"
      recreate: true
